// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"github.com/haidang666/go-app/internal/domain/repository"
	"github.com/haidang666/go-app/internal/domain/use_case/auth"
	auth2 "github.com/haidang666/go-app/internal/infrastructure/http/module_route/auth"
	"github.com/haidang666/go-app/internal/infrastructure/http/router"
	"github.com/haidang666/go-app/internal/infrastructure/repository"
)

// Injectors from wire.go:

// InitializeContainer initializes and returns the application container
// This function is implemented by the wire code generator
func InitializeContainer() (*Container, error) {
	userRepository := ProvideUserRepository()
	signUpUseCase := ProvideSignUpUseCase(userRepository)
	authHandler := ProvideAuthHandler(signUpUseCase)
	mux := ProvideRouter(authHandler)
	container := ProvideContainer(mux)
	return container, nil
}

// wire.go:

// Providers for the application container
var ProviderSet = wire.NewSet(
	ProvideUserRepository,
	ProvideSignUpUseCase,
	ProvideAuthHandler,
	ProvideRouter,
	ProvideContainer,
)

// ProvideUserRepository provides the user repository implementation
func ProvideUserRepository() repository.UserRepository {
	return infrastructure.NewUserRepository()
}

// ProvideSignUpUseCase provides the sign up use case
func ProvideSignUpUseCase(userRepo repository.UserRepository) *auth.SignUpUseCase {
	return auth.NewSignUpUseCase(userRepo)
}

// ProvideAuthHandler provides the auth handler
func ProvideAuthHandler(signUpUseCase *auth.SignUpUseCase) *auth2.AuthHandler {
	return auth2.NewAuthHandler(auth2.NewAuthHandlerArgs{
		SignUpUseCase: signUpUseCase,
	})
}

// ProvideRouter provides the chi router with all routes registered
func ProvideRouter(authHandler *auth2.AuthHandler) *chi.Mux {
	return router.NewRouter(router.NewRouterArgs{
		AuthHandler: authHandler,
	})
}

// ProvideContainer provides the application container
func ProvideContainer(r *chi.Mux) *Container {
	return &Container{
		Status: 1,
		Router: r,
	}
}
